// Copyright (c) 2025 Christian Flessa. All rights reserved.
// This file is licensed under the MIT license. See LICENSE in the project root for more information.
namespace Chaos.Mongo.EventStore;

using Chaos.Mongo.EventStore.Integrity;

/// <summary>
/// Abstract base class for domain events targeting a specific aggregate type.
/// </summary>
/// <typeparam name="TAggregate">The aggregate type this event applies to.</typeparam>
public abstract class Event<TAggregate> where TAggregate : class, IAggregate, new()
{
    /// <summary>
    /// Gets or sets the identifier of the aggregate this event belongs to.
    /// </summary>
    public Guid AggregateId { get; set; }

    /// <summary>
    /// Gets or sets the discriminator string for the aggregate type.
    /// Set automatically by the event store.
    /// </summary>
    public String AggregateType { get; set; } = String.Empty;

    /// <summary>
    /// Gets or sets the UTC timestamp of when the event was created.
    /// Set automatically by the event store on append if not provided.
    /// </summary>
    public DateTime CreatedUtc { get; set; }

    /// <summary>
    /// Gets or sets the unique event identifier.
    /// Used for idempotency: duplicate event IDs are rejected by the unique index on <c>_id</c>.
    /// Generated by the event store on append if left unset; supply it explicitly to control idempotency.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the aggregate revision after this event: the number of state-changing events up to and
    /// including this one. An <see cref="ObservationalEvent{TAggregate}"/> records the revision it observed.
    /// Set automatically by the event store on append; caller-supplied values are overwritten.
    /// </summary>
    public Int64 Revision { get; set; }

    /// <summary>
    /// Gets or sets the position of this event in its aggregate's stream.
    /// Must be set by the caller to sequential values starting from the stream's highest position + 1.
    /// The event store validates that positions are sequential with no gaps.
    /// </summary>
    public Int64 Version { get; set; }

    /// <summary>
    /// Gets or sets the integrity data that seals this event into its stream's hash chain.
    /// Stored in the reserved <c>_integrity</c> element; <c>null</c> for events of unprotected streams.
    /// </summary>
    internal EventIntegrity? Integrity { get; set; }

    /// <summary>
    /// Applies this event's changes to the given aggregate instance.
    /// </summary>
    /// <param name="aggregate">The aggregate to modify.</param>
    public abstract void Execute(TAggregate aggregate);
}
